### ISSUE TITLE
Logstash error with sflow codec

### ISSUE THREAD

**Issue by AMyltsev** [path-network/logstash-codec-sflow#7]
Hello,
I have error if use sflow codec for logstash. After this error input stop working.
```
[2017-09-12T18:18:34,440][ERROR][logstash.inputs.udp      ] 
Exception in inputworker
 {"exception"=>#<EOFError: End of file reached>,
  "backtrace"=>["/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/io.rb:314:in `read'",
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/io.rb:276:in `readbytes'", 
  "(eval):23:in `read_and_return_value'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/base_primitive.rb:129:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "(eval):2:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "(eval):2:in `do_read'", "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "(eval):2:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lifgb/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "(eval):2:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "(eval):2:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/array.rb:322:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/array.rb:322:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "(eval):2:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/array.rb:322:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/array.rb:322:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "org/jruby/RubyArray.java:1613:in `each'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/struct.rb:139:in `do_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/base.rb:147:in `read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/base.rb:254:in `start_read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/base.rb:145:in `read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/bindata-2.4.0/lib/bindata/base.rb:21:in `read'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-codec-sflow-2.0.0/lib/logstash/codecs/sflow.rb:105:in `decode'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.rb:118:in `inputworker'", 
  "/usr/share/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-udp-3.1.0/lib/logstash/inputs/udp.:89:in `udp_listener'"]}
```
I found exact packets which are cause of this error.
[EOFError packets.zip](https://github.com/ashangit/logstash-codec-sflow/files/1310000/EOFError.packets.zip)

regards,
Aleksey

**Comment by AMyltsev** [comment]
This patch #6 should solve this issue
